In [22]:
import pandas as pd
import numpy as np

In [2]:
maternal =pd.read_clipboard()

In [7]:
maternal.tail()

                                       Input variable         Outcome variable
55  Performed permanent methods out of total (than...  Maternal mortality rate
56                        Rate of distributed condoms  Maternal mortality rate
57                                IMCI underweight, %  Maternal mortality rate
58                               Child mortality rate  Maternal mortality rate
59                                   IMCI stunting, %  Maternal mortality rate

In [4]:
under5 =pd.read_clipboard()

In [6]:
under5.tail()

                                       Input variable   Outcome variable
63  Rate of performed permanant method (female, to...  Under-5 mortality
64        Rate of performed permanant method (normal)  Under-5 mortality
65                           Rate of distributed ECPs  Under-5 mortality
66                            Maternal mortality rate  Under-5 mortality
67                              PCV vial wastage rate  Under-5 mortality

In [8]:
antenatal = pd.read_clipboard()

In [9]:
antenatal.tail()

                                 Input variable    Outcome variable
82   Rate of performed permanant method (total)  Antenatal coverage
83  Rate of performed permanant method (normal)  Antenatal coverage
84              Proportion of registered births  Antenatal coverage
85                     Rate of distributed ECPs  Antenatal coverage
86                      Maternal mortality rate  Antenatal coverage

In [10]:
unmet = pd.read_clipboard()

In [11]:
unmet.head()

                            Input variable                Outcome variable
0   Rate of distributed misoprostol (dose)  Unmet need for family planning
1          Rate of distributed MRMs (pack)  Unmet need for family planning
2  Rate of distributed implant EEW (total)  Unmet need for family planning
3      DHS: Proportion of rural population  Unmet need for family planning
4        Rate of distributed IUDs (normal)  Unmet need for family planning

In [12]:
all_vars = maternal.merge(under5, how='outer', on='Input variable')
all_vars.head()

,Input variable,Outcome variable_x,Outcome variable_y
0,Pentavalent 1 to MR 2 dropout rate,Maternal mortality rate,NaN
1,Differences between Pentavalent doses and vial...,Maternal mortality rate,NaN
2,PCV vial wastage rate,Maternal mortality rate,Under-5 mortality
3,Pentavalent vial use and doses ratio,Maternal mortality rate,NaN
4,Pentavalent vial wastage rate,Maternal mortality rate,NaN

In [13]:
all_vars = all_vars.merge(unmet, how='outer', on='Input variable')
all_vars.head()

,Input variable,Outcome variable_x,Outcome variable_y,Outcome variable
0,Pentavalent 1 to MR 2 dropout rate,Maternal mortality rate,NaN,NaN
1,Differences between Pentavalent doses and vial...,Maternal mortality rate,NaN,NaN
2,PCV vial wastage rate,Maternal mortality rate,Under-5 mortality,NaN
3,Pentavalent vial use and doses ratio,Maternal mortality rate,NaN,NaN
4,Pentavalent vial wastage rate,Maternal mortality rate,NaN,NaN

In [14]:
all_vars = all_vars.merge(antenatal, how='outer', on='Input variable')

In [15]:
all_vars.head()

,Input variable,Outcome variable_x,Outcome variable_y,Outcome variable_x,Outcome variable_y
0,Pentavalent 1 to MR 2 dropout rate,Maternal mortality rate,NaN,NaN,NaN
1,Differences between Pentavalent doses and vial...,Maternal mortality rate,NaN,NaN,Antenatal coverage
2,PCV vial wastage rate,Maternal mortality rate,Under-5 mortality,NaN,NaN
3,Pentavalent vial use and doses ratio,Maternal mortality rate,NaN,NaN,Antenatal coverage
4,Pentavalent vial wastage rate,Maternal mortality rate,NaN,NaN,NaN

In [17]:
all_vars.columns = ['Input variable', 'Maternal mortality rate', 'Under-5 mortality',
                    'Unmet need for family planning', 'Antenatal coverage']

In [18]:
all_vars.head()

,Input variable,Maternal mortality rate,Under-5 mortality,Unmet need for family planning,Antenatal coverage
0,Pentavalent 1 to MR 2 dropout rate,Maternal mortality rate,NaN,NaN,NaN
1,Differences between Pentavalent doses and vial...,Maternal mortality rate,NaN,NaN,Antenatal coverage
2,PCV vial wastage rate,Maternal mortality rate,Under-5 mortality,NaN,NaN
3,Pentavalent vial use and doses ratio,Maternal mortality rate,NaN,NaN,Antenatal coverage
4,Pentavalent vial wastage rate,Maternal mortality rate,NaN,NaN,NaN

In [20]:
print(all_vars['Maternal mortality rate'].value_counts())
print(all_vars['Under-5 mortality'].value_counts())
print(all_vars['Unmet need for family planning'].value_counts())
print(all_vars['Antenatal coverage'].value_counts())

Maternal mortality rate    60
Name: Maternal mortality rate, dtype: int64
Under-5 mortality    68
Name: Under-5 mortality, dtype: int64
Unmet need for family planning    116
Name: Unmet need for family planning, dtype: int64
Antenatal coverage    87
Name: Antenatal coverage, dtype: int64

In [23]:
all_vars['Maternal mortality rate'] = np.where(all_vars['Maternal mortality rate']=='Maternal mortality rate', 'Yes', 'No')
all_vars['Under-5 mortality'] = np.where(all_vars['Under-5 mortality']=='Under-5 mortality', 'Yes', 'No')
all_vars['Unmet need for family planning'] = np.where(all_vars['Unmet need for family planning']=='Unmet need for family planning', 'Yes', 'No')
all_vars['Antenatal coverage'] = np.where(all_vars['Antenatal coverage']=='Antenatal coverage', 'Yes', 'No')
all_vars.head()

,Input variable,Maternal mortality rate,Under-5 mortality,Unmet need for family planning,Antenatal coverage
0,Pentavalent 1 to MR 2 dropout rate,Yes,No,No,No
1,Differences between Pentavalent doses and vial...,Yes,No,No,Yes
2,PCV vial wastage rate,Yes,Yes,No,No
3,Pentavalent vial use and doses ratio,Yes,No,No,Yes
4,Pentavalent vial wastage rate,Yes,No,No,No

In [24]:
all_vars.to_excel("/Users/edinhamzic/Symphony/wb_bangladesh/Bangladesh/output/all/variable_matrix.xlsx", sheet_name='Matrix')