# Tables: Unmet needs

In [2]:
import pandas as pd

In [3]:
DATA = '/Users/edinhamzic/Symphony/wb_bangladesh/Bangladesh/output/all/'
clusters_intersect_all = 'clusters_unmet_needs_vars_intersect_all.csv'
clusters_intersect_2016 = 'clusters_unmet_needs_vars_intersect_2016.csv'
clusters_intersect_2011 = 'clusters_unmet_needs_vars_intersect_2011.csv'
clusters_union_all = 'clusters_unmet_needs_vars_union_all.csv'
clusters_union_2016 = 'clusters_unmet_needs_vars_union_2016.csv'
clusters_union_2011 = 'clusters_unmet_needs_vars_union_2011.csv'
corr_2016 = 'corr_unmet_needs_2016.csv'
cca_2016 = 'cca_unmet_needs_2016.csv'
corr_2011 = 'corr_unmet_needs_2011.csv'
cca_2011 = 'cca_unmet_needs_2011.csv'
corr_cca = [corr_2011, cca_2011, corr_2016, cca_2016]

In [4]:
def read_corr_cca(dir_path, files_list):
    data_dict = {}
    for file in files_list:
        data_dict[file] = pd.read_csv(dir_path+file)
    return data_dict

## Summary tables

In [5]:
clusters_intersect = pd.read_csv(DATA+clusters_intersect_all)
clusters_union = pd.read_csv(DATA+clusters_union_all)

In [6]:
clusters_intersect_summ = clusters_intersect.groupby(['cluster', 'year']).median().transpose()
clusters_union_summ = clusters_union.groupby(['cluster', 'year']).median().transpose()

In [7]:
display(clusters_intersect_summ.head())
clusters_intersect_summ.to_csv(DATA+'/unmetneeds_summaries/unmetneeds_intersect.csv')

cluster                                               0               1  \
year                                               2011    2016    2011
DHS: Dependency ratio                            80.345  68.640  75.895
Distributed condoms out of total (thana), %       6.420   6.920   9.600
Proportion of women population                   48.335  49.175  49.665
Pneumonia reported at facility, %                 5.245   6.205   7.540
DHS: Proportion of females as head of household   6.755  13.090  15.300

cluster                                                       2         \
year                                               2016    2011   2016
DHS: Dependency ratio                            75.515  64.805  58.43
Distributed condoms out of total (thana), %      11.020   5.685   6.80
Proportion of women population                   50.230  49.405  49.85
Pneumonia reported at facility, %                 7.645   4.650   6.14
DHS: Proportion of females as head of household  15.495   4.015   4.99

cluster                                               3
year                                               2011   2016
DHS: Dependency ratio                            55.615  59.45
Distributed condoms out of total (thana), %      10.370  10.72
Proportion of women population                   49.210  49.69
Pneumonia reported at facility, %                 6.580   5.74
DHS: Proportion of females as head of household   7.015   8.56

In [8]:
display(clusters_union_summ.head())
clusters_union_summ.to_csv(DATA+'/unmetneeds_summaries/unmetneeds_union.csv')

cluster                                                    0           \
year                                                    2011     2016
Crude coverage BCG, %                               99.10000  99.8000
Vitamin A coverage children 12-59 months, %         88.30000  91.2000
Performed permanent methods out of total (thana...   3.02500   3.7400
Contraceptive acceptance rate (thana), %            76.41000  79.4100
Proportion of cases with puerperal sepsis among...   0.00245   0.0014

cluster                                                   1           \
year                                                   2011     2016
Crude coverage BCG, %                               98.1500  99.0000
Vitamin A coverage children 12-59 months, %         94.0500  89.1500
Performed permanent methods out of total (thana...   1.8100   3.6950
Contraceptive acceptance rate (thana), %            74.3900  78.3000
Proportion of cases with puerperal sepsis among...   0.0026   0.0007

cluster                                                    2            \
year                                                    2011      2016
Crude coverage BCG, %                               99.50000  100.5000
Vitamin A coverage children 12-59 months, %         94.05000   93.7000
Performed permanent methods out of total (thana...   5.09500    4.4500
Contraceptive acceptance rate (thana), %            78.94000   77.5200
Proportion of cases with puerperal sepsis among...   0.00095    0.0009

cluster                                                   3
year                                                   2011      2016
Crude coverage BCG, %                               101.450  102.0000
Vitamin A coverage children 12-59 months, %          95.450   90.6000
Performed permanent methods out of total (thana...    1.105    2.2600
Contraceptive acceptance rate (thana), %             78.485   78.2100
Proportion of cases with puerperal sepsis among...    0.001    0.0017

## Outcome variable

In [13]:
ALL2011 = '/Users/edinhamzic/Symphony/wb_bangladesh/Bangladesh/output/all/all2011.csv'
ALL2016 = '/Users/edinhamzic/Symphony/wb_bangladesh/Bangladesh/output/all/all2016.csv'
all2011 = pd.read_csv(ALL2011)
clusters_intersect2011 = pd.read_csv(DATA+clusters_intersect_2011)
all2016 = pd.read_csv(ALL2016)
clusters_intersect2016 = pd.read_csv(DATA+clusters_intersect_2016)
all2011 = all2011.merge(clusters_intersect2011[['DistrictName', 'cluster', ]], how='left', on='DistrictName')
all2016 = all2016.merge(clusters_intersect2016[['DistrictName', 'cluster', ]], how='left', on='DistrictName')
display(all2011[['prop_unmet_need_family_planing', 'cluster']].groupby('cluster').median().transpose())
display(all2016[['prop_unmet_need_family_planing', 'cluster']].groupby('cluster').median().transpose())

cluster                             0       1      2      3
prop_unmet_need_family_planing  13.65  20.035  9.485  10.06

cluster                              0      1     2      3
prop_unmet_need_family_planing  12.975  15.41  8.67  10.12

## Correlations

In [8]:
corr_cca = read_corr_cca(dir_path=DATA,files_list=corr_cca)
for key, value in corr_cca.items():
    print(key)
    display(value.head())
    display(value.shape)

corr_unmet_needs_2011.csv

,index,DHS: Unmet need for family planning,abs_prop_unmet_need_family_planing,p_value
0,DHS: Proportion of use of current contraceptiv...,-0.831776,0.831776,1.708276e-17
1,Dependency ratio,0.633349,0.633349,1.949960e-08
2,"Distributed IUDs out of total (thana), %",0.617231,0.617231,5.572988e-08
3,"Distributed IUDs out of total (month, thana), %",0.617231,0.617231,5.572988e-08
4,DHS: Sex ratio (males / females),-0.548085,0.548085,2.760155e-06

(80, 4)

cca_unmet_needs_2011.csv

                       Indicators  CCA_coeff  CCA_coeff_abs
0                      Death rate  -0.161607       0.161607
1  Proportion of women population   0.122904       0.122904
2                Dependency ratio   0.176366       0.176366
3                       Sex ratio  -0.118884       0.118884
4       Proportion of live births   0.105973       0.105973

(25, 3)

corr_unmet_needs_2016.csv

,index,DHS: Unmet need for family planning,abs_prop_unmet_need_family_planing,p_value
0,DHS: Proportion of use of current contraceptiv...,-0.839687,0.839687,4.346822e-18
1,DHS: Dependency ratio,0.652078,0.652078,5.319055e-09
2,DHS: Proportion of females as head of household,0.426293,0.426293,4.442170e-04
3,Performed permanent methods out of total (than...,0.378648,0.378648,2.033911e-03
4,Performed permanent methods out of total (mont...,0.378611,0.378611,2.036142e-03

(27, 4)

cca_unmet_needs_2016.csv

                                     Indicators  CCA_coeff  CCA_coeff_abs
0  Crude coverage measles children 23 months, %   0.127010       0.127010
1   Vitamin A coverage children 12-59 months, %   0.117877       0.117877
2             Proportion of women (15-45 years)  -0.155142       0.155142
3                                Fertility rate   0.139743       0.139743
4                    Proportion of rural deaths  -0.112983       0.112983

(26, 3)